spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbprueba
    username: root
    password: MySQL
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: false
    
    
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dbprueba
    username: admin
    password: postgresql
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: false    